# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elkr.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'elkr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nelkr.proto\x12\x04\x65lkr\"\x1e\n\x0e\x41\x64\x64SinkRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"+\n\x0f\x41\x64\x64SinkResponse\x12\x18\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.elkr.Code\"!\n\x11RemoveSinkRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\".\n\x12RemoveSinkResponse\x12\x18\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.elkr.Code\"\x12\n\x10ListSinksRequest\"<\n\x11ListSinksResponse\x12\x18\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.elkr.Code\x12\r\n\x05sinks\x18\x17 \x03(\t*D\n\x04\x43ode\x12\r\n\tCODE_NULL\x10\x00\x12\x07\n\x02OK\x10\xc8\x01\x12\x11\n\x0c\x43LIENT_ERROR\x10\x90\x03\x12\x11\n\x0cSERVER_ERROR\x10\xf4\x03\x32\xc4\x01\n\x0b\x45lkrService\x12\x36\n\x07\x41\x64\x64Sink\x12\x14.elkr.AddSinkRequest\x1a\x15.elkr.AddSinkResponse\x12?\n\nRemoveSink\x12\x17.elkr.RemoveSinkRequest\x1a\x18.elkr.RemoveSinkResponse\x12<\n\tListSinks\x12\x16.elkr.ListSinksRequest\x1a\x17.elkr.ListSinksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elkr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODE']._serialized_start=262
  _globals['_CODE']._serialized_end=330
  _globals['_ADDSINKREQUEST']._serialized_start=20
  _globals['_ADDSINKREQUEST']._serialized_end=50
  _globals['_ADDSINKRESPONSE']._serialized_start=52
  _globals['_ADDSINKRESPONSE']._serialized_end=95
  _globals['_REMOVESINKREQUEST']._serialized_start=97
  _globals['_REMOVESINKREQUEST']._serialized_end=130
  _globals['_REMOVESINKRESPONSE']._serialized_start=132
  _globals['_REMOVESINKRESPONSE']._serialized_end=178
  _globals['_LISTSINKSREQUEST']._serialized_start=180
  _globals['_LISTSINKSREQUEST']._serialized_end=198
  _globals['_LISTSINKSRESPONSE']._serialized_start=200
  _globals['_LISTSINKSRESPONSE']._serialized_end=260
  _globals['_ELKRSERVICE']._serialized_start=333
  _globals['_ELKRSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
